name: Generate Documentation (PHP + TypeScript)

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TypeDoc
        run: |
          npm install typedoc typedoc-plugin-markdown

      - name: Download phpDocumentor
        run: curl -L -o phpDocumentor.phar https://github.com/phpDocumentor/phpDocumentor/releases/latest/download/phpDocumentor.phar

      - name: Generate PHP Documentation
        run: php phpDocumentor.phar --directory logistics2 --target docs/logistics2-php

      - name: Generate TypeScript Documentation
        run: npx typedoc --entryPoints application/logistics2-mobile --out docs/logistics2-mobile

      - name: Commit and Push Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Update PHP and TS docs [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
